/**
 * CreateUserModal.js
 *
 * Reusable modal for provisioning a user account from the admin panel.
 * Captures email, a password (auto-generated by default), display name, an
 * optional admin flag, and optional demo grants. On success it calls the
 * `createUser` callable and hands the result back via `onCreated`.
 *
 * Used by UsersTab ("Crear usuario") and LeadsTab ("Crear cuenta desde pedido").
 */

import { createUser, DEMO_PRODUCTS } from '../services/AdminService.js';
import { escapeHtml, showToast, lockBodyScroll, unlockBodyScroll } from '../../utils/DomHelper.js';

/**
 * Generates a reasonably strong, human-typable temporary password.
 * @returns {string}
 */
function generatePassword() {
  const chars = 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz23456789';
  let out = '';
  for (let i = 0; i < 12; i += 1) {
    out += chars[Math.floor(Math.random() * chars.length)];
  }
  return out;
}

/**
 * Opens the create-user modal.
 * @param {Object} [options]
 * @param {{ email?: string, displayName?: string, solutionType?: string }} [options.prefill]
 * @param {(result: { uid: string, email: string }) => void} [options.onCreated]
 */
export function openCreateUserModal({ prefill = {}, onCreated } = {}) {
  const initialPassword = generatePassword();
  const presetProduct = DEMO_PRODUCTS.find(p => p.id === prefill.solutionType)?.id || '';

  const overlay = document.createElement('div');
  overlay.className = 'admin-modal';
  overlay.innerHTML = `
    <div class="admin-modal__backdrop" data-close></div>
    <div class="admin-modal__panel" role="dialog" aria-modal="true" aria-labelledby="create-user-title">
      <div class="admin-modal__head">
        <h2 class="admin-modal__title" id="create-user-title">Crear usuario</h2>
        <button class="admin-modal__close" type="button" data-close aria-label="Cerrar">✕</button>
      </div>

      <form id="create-user-form" class="admin-modal__body" novalidate>
        <label class="admin-field">
          <span class="admin-field__label">Email</span>
          <input class="admin-input" id="cu-email" type="email" autocomplete="off"
                 placeholder="cliente@email.com" value="${escapeHtml(prefill.email || '')}" required />
        </label>

        <label class="admin-field">
          <span class="admin-field__label">Nombre y apellido</span>
          <input class="admin-input" id="cu-name" type="text" autocomplete="off"
                 placeholder="Nombre del cliente" value="${escapeHtml(prefill.displayName || '')}" />
        </label>

        <label class="admin-field">
          <span class="admin-field__label">Contraseña temporal</span>
          <div class="admin-modal__inline">
            <input class="admin-input" id="cu-password" type="text" autocomplete="off"
                   value="${escapeHtml(initialPassword)}" minlength="6" required />
            <button class="admin-button" id="cu-generate" type="button">Generar</button>
          </div>
          <span class="admin-field__hint">Compartila con el cliente. Puede cambiarla desde "¿Olvidaste tu contraseña?".</span>
        </label>

        <label class="admin-checkbox">
          <input type="checkbox" id="cu-admin" />
          <span>Otorgar permisos de administrador</span>
        </label>

        <div class="admin-field">
          <span class="admin-field__label">Otorgar prueba (opcional)</span>
          <div class="admin-modal__inline">
            <select class="admin-input" id="cu-demo-product">
              <option value="">Sin prueba</option>
              ${DEMO_PRODUCTS.map(p => `<option value="${escapeHtml(p.id)}"${p.id === presetProduct ? ' selected' : ''}>${escapeHtml(p.label)}</option>`).join('')}
            </select>
            <label class="admin-field admin-field--inline">
              <span class="admin-field__label">Días</span>
              <input class="admin-input admin-input--num" id="cu-demo-days" type="number" min="1" max="365" value="7" />
            </label>
          </div>
        </div>

        <div class="admin-modal__actions">
          <button class="admin-button" type="button" data-close>Cancelar</button>
          <button class="admin-button admin-button--primary" id="cu-submit" type="submit">Crear usuario</button>
        </div>
      </form>
    </div>
  `;

  document.body.appendChild(overlay);
  lockBodyScroll();

  const close = () => { overlay.remove(); unlockBodyScroll(); };
  overlay.querySelectorAll('[data-close]').forEach(el => el.addEventListener('click', close));
  overlay.addEventListener('keydown', (e) => { if (e.key === 'Escape') close(); });

  overlay.querySelector('#cu-generate')?.addEventListener('click', () => {
    const pwd = overlay.querySelector('#cu-password');
    if (pwd) pwd.value = generatePassword();
  });

  overlay.querySelector('#create-user-form')?.addEventListener('submit', async (e) => {
    e.preventDefault();
    const email = overlay.querySelector('#cu-email')?.value.trim() || '';
    const displayName = overlay.querySelector('#cu-name')?.value.trim() || '';
    const password = overlay.querySelector('#cu-password')?.value || '';
    const admin = overlay.querySelector('#cu-admin')?.checked || false;
    const demoProduct = overlay.querySelector('#cu-demo-product')?.value || '';
    const demoDays = parseInt(overlay.querySelector('#cu-demo-days')?.value, 10) || 7;

    if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      showToast('Ingresá un email válido.', 'error');
      return;
    }
    if (password.length < 6) {
      showToast('La contraseña debe tener al menos 6 caracteres.', 'error');
      return;
    }

    const demos = demoProduct ? [{ productId: demoProduct, days: demoDays }] : [];

    const submitBtn = overlay.querySelector('#cu-submit');
    if (submitBtn) { submitBtn.disabled = true; submitBtn.textContent = 'Creando…'; }

    try {
      const result = await createUser({ email, password, displayName, admin, demos });
      showToast('Usuario creado', 'success');
      close();
      if (typeof onCreated === 'function') onCreated(result);
    } catch (err) {
      console.error('CreateUserModal: create failed', err);
      const msg = err.code === 'functions/already-exists'
        ? 'Ya existe una cuenta con ese email.'
        : err.message || 'No pudimos crear el usuario.';
      showToast(msg, 'error');
      if (submitBtn) { submitBtn.disabled = false; submitBtn.textContent = 'Crear usuario'; }
    }
  });
}
